fix(test): handle thread id after name in panic
In recent versions of Rust, the panic message includes
a thread id after the thread name:

    thread 'main' (6543) panicked at src/main.rs:3:5:

causing a failure to parse diagnostic info in
rustaceanvim.test.

This patch modifies the regular expressions to allow
for a thread id between the thread name and the word
"panicked".